### ISSUE TITLE
how to translate the feature map to the GH-Feature?

### ISSUE THREAD

**Issue by WangQinghuCS** [genforce/ghfeat#1]
Hi, thanks for your work. I want to do some experiments based on your work. Howerer, in your paper, the detail of encoder structure didn't show how to translate the feature map(eg, 1024*4*4) to the GH-Feat(512*1). Can you provide it? Thank you very much!

**Comment by ShenYujun** [comment]
We will update the [paper on arXiv](https://arxiv.org/pdf/2007.10379.pdf) very soon, which provides more details on the network structure. Also, we are preparing to release the code right now. Please stay tuned.

**Comment by ShenYujun** [comment]
The code and paper are both updated :)
